## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(columns = ["EIN", "NAME"])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE
apptype_count = application_df["APPLICATION_TYPE"].value_counts()
apptype_count

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace = list(apptype_count[apptype_count < 528].index)
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE
classification_count = application_df["CLASSIFICATION"].value_counts()
classification_count

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
filtered_classification_count = classification_count.loc[classification_count > 1]
filtered_classification_count

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = list(classification_count[classification_count < 104].index)
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
application_dummies = pd.get_dummies(application_df)

In [11]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
X = application_dummies.drop(columns = ["IS_SUCCESSFUL"])
y = application_dummies["IS_SUCCESSFUL"]

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [21]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 80
hidden_nodes_layer2 = 30
hidden_nodes_layer3 = 15

nn2 = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn2.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim = input_features, activation = "relu"))

# Second hidden layer
#  YOUR CODE GOES HERE
nn2.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

#Third hidden layer
nn2.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

# Output layer
#  YOUR CODE GOES HERE
nn2.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 80)                4000

 dense_7 (Dense)             (None, 30)                2430

 dense_8 (Dense)             (None, 15)                465

 dense_9 (Dense)             (None, 1)                 16

=================================================================
Total params: 6911 (27.00 KB)
Trainable params: 6911 (27.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [22]:
# Compile the model
#  YOUR CODE GOES HERE
nn2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [23]:
# Train the model
#  YOUR CODE GOES HERE
nn2_fit = nn2.fit(X_train_scaled, y_train, epochs = 100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5686 - accuracy: 0.7208
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5515 - accuracy: 0.7320
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5486 - accuracy: 0.7338
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7351
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7347
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5438 - accuracy: 0.7365
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7354
Epoch 8/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5429 - accuracy: 0.7360
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7364
Epoch 10/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7363
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7374
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7380
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7377
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7373
Epoch 15/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7385
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7381
Epoch 17/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5393 - accuracy: 0.7377
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7390
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5379 - accuracy: 0.7382
Epoch 20/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5379 - accuracy: 0.7401
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5379 - accuracy: 0.7390
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7389
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7393
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7394
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5363 - accuracy: 0.7398
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5364 - accuracy: 0.7395
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7398
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7402
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7402
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7392
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7400
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7405
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5352 - accuracy: 0.7401
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5352 - accuracy: 0.7393
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7403
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7404
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7401
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7415
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7404
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7406
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7403
Epoch 42/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5338 - accuracy: 0.7411
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5336 - accuracy: 0.7402
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7406
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7407
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7410
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7414
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7405
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7419
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7409
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5330 - accuracy: 0.7415
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7417
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7410
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7415
Epoch 55/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7414
Epoch 56/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7414
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7412
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7407
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5319 - accuracy: 0.7414
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5321 - accuracy: 0.7418
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7410
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5319 - accuracy: 0.7414
Epoch 63/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7414
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5317 - accuracy: 0.7414
Epoch 65/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5315 - accuracy: 0.7422
Epoch 66/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7414
Epoch 67/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5316 - accuracy: 0.7416
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5316 - accuracy: 0.7418
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7421
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5313 - accuracy: 0.7414
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7425
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5317 - accuracy: 0.7418
Epoch 73/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5308 - accuracy: 0.7417
Epoch 74/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5314 - accuracy: 0.7424
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5307 - accuracy: 0.7422
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5315 - accuracy: 0.7426
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5307 - accuracy: 0.7423
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5309 - accuracy: 0.7423
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7428
Epoch 80/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5306 - accuracy: 0.7421
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7428
Epoch 82/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7424
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5304 - accuracy: 0.7418
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5304 - accuracy: 0.7420
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5304 - accuracy: 0.7426
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5300 - accuracy: 0.7424
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5301 - accuracy: 0.7418
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7430
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5302 - accuracy: 0.7416
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5301 - accuracy: 0.7425
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7416
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5302 - accuracy: 0.7423
Epoch 93/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5300 - accuracy: 0.7421
Epoch 94/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5300 - accuracy: 0.7428
Epoch 95/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5296 - accuracy: 0.7430
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5302 - accuracy: 0.7426
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5292 - accuracy: 0.7427
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5293 - accuracy: 0.7432
Epoch 99/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7418
Epoch 100/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7423

In [24]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn2.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5715 - accuracy: 0.7231 - 427ms/epoch - 2ms/step
Loss: 0.5715014934539795, Accuracy: 0.7231487035751343

In [25]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
model = nn2
model.save("AlphabetSoupCharity_Optimization.h5")